### ISSUE TITLE
Backend: ACH management server

### ISSUE THREAD

**Issue by aaronmboyd** [humanity-cash/local-currency-core#14]
The system and app users need to know when Berkshares have been credited and ready to use.

- [x] Polling server / on target FBO or omnibus account (check that ACH has settled and funds received in reserve account). There may not be a fully deterministic way to determine ACH settlement, as returns may occur. #26 
- [ ] ~Handle NSF / ACH returns, probably go into a queue for manual reconciliation / customer support in lieu of a fully automated retry and fall-off system #27~ 
- [x] Mint the Berkshares, directly on-chain interaction with smart contract suite #26 
- [x] Burn the Berkshares, when redemption requested via interaction with smart contract suite #26 
- [x] (Implicit) Balance in BerkShares app updated accordingly, with a notification
