### ISSUE TITLE
Backend: API that responds to the App and interacts with the smart contract suite on chain

### ISSUE THREAD

**Issue by aaronmboyd** [humanity-cash/local-currency-core#7]
Public functions
- [x] Blockchain - view - get health #15 
- [x] Blockchain - view - get users (by ID) #16 
- [x] Blockchain - view - get users (all) #16 
- [x] Blockchain - view - get transactions (for user) #17 
- [x] Blockchain - view - get transactions (all) #17 
- [x] Blockchain - view - get minting / redemption statistics (current balance minted against each local bank) #18

Administrative functions
- [x] Blockchain - write - create local currency user #19
- [x] Blockchain - write - deposit / mint currency #20
- [x] Blockchain - write - wtihdraw / burn currency #21
- [x] Blockchain - write - create transaction #22 
- [x] Blockchain - write - emergency pause #23 
- [x] Data - write - store consent #24 
- [x] Data - write - store KYC #25
